In [27]:
import torch
from torch.nn.functional import normalize

In [29]:
normals = torch.tensor([[1.0, 3, 4],
                       [2, 2, 5],
                       [3, 2, 5]])


In [21]:
normalized_normals = normals / torch.sqrt(torch.sum(torch.pow(normals, 2), axis=1))

In [22]:
print(normalized_normals)

tensor([[0.1961, 0.5222, 0.6489],
        [0.3922, 0.3482, 0.8111],
        [0.5883, 0.3482, 0.8111]])


In [23]:
def normalize_vector(v):
    return v / torch.sqrt(v[0] ** 2 + v[1] ** 2 + v[2] ** 2)

In [24]:
print(torch.pow(normals, 2))

tensor([[ 1,  9, 16],
        [ 4,  4, 25],
        [ 9,  4, 25]])


In [25]:
def normalize_normals(normals):
    normalized_normals = []
    num_triangles = len(normals)

    for i in range(num_triangles):
        normalized_normals.append(normalize_vector(normals[i]))

    return normalized_normals

In [26]:
normalize_normals(normals)

[tensor([0.1961, 0.5883, 0.7845]),
 tensor([0.3482, 0.3482, 0.8704]),
 tensor([0.4867, 0.3244, 0.8111])]

# library

In [31]:
normalize(normals, dim=1)

tensor([[0.1961, 0.5883, 0.7845],
        [0.3482, 0.3482, 0.8704],
        [0.4867, 0.3244, 0.8111]])